import { rien, sonne, legere, grave, critique, tueNet } from './woundResults';

export const woundTable = {
  1: {
    '-1': rien,
    0: sonne,
    1: sonne,
    2: legere,
    3: legere,
    4: legere,
    5: grave,
    6: grave,
    7: grave,
    8: critique,
    9: critique,
  },
  2: {
    '-1': sonne,
    0: sonne,
    1: legere,
    2: legere,
    3: grave,
    4: grave,
    5: grave,
    6: critique,
    7: critique,
    8: critique,
    9: tueNet,
  },
  3: {
    '-1': sonne,
    0: legere,
    1: legere,
    2: grave,
    3: grave,
    4: critique,
    5: critique,
    6: critique,
    7: tueNet,
    8: tueNet,
    9: tueNet,
  },
  4: {
    '-1': legere,
    0: legere,
    1: grave,
    2: grave,
    3: critique,
    4: critique,
    5: tueNet,
    6: tueNet,
    7: tueNet,
    8: tueNet,
    9: tueNet,
  },
  5: {
    '-1': legere,
    0: grave,
    1: critique,
    2: critique,
    3: tueNet,
    4: tueNet,
    5: tueNet,
    6: tueNet,
    7: tueNet,
    8: tueNet,
    9: tueNet,
  },
  6: {
    '-1': legere,
    0: grave,
    1: critique,
    2: critique,
    3: tueNet,
    4: tueNet,
    5: tueNet,
    6: tueNet,
    7: tueNet,
    8: tueNet,
    9: tueNet,
  },
};
